---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: debian
    image: quay.io/nleiva/grafana-agent-role-debian
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible

verifier:
  name: ansible
